# Generated by Django 3.2.25 on 2025-06-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=100)),
                ('categoria_pelicula', models.CharField(choices=[('Terror', 'Terror'), ('Comedia', 'Comedia'), ('Romance', 'Romance'), ('Fantasía', 'Fantasía'), ('Thriller', 'Thriller'), ('Infantil', 'Infantil'), ('Drama', 'Drama'), ('Triste', 'Triste'), ('Animadas', 'Animadas'), ('Deportes', 'Deportes')], max_length=20)),
                ('lanzamiento_pelicula', models.DateField()),
                ('reseña_pelicula', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
